### ISSUE TITLE
aptly db cleanup considers conflicting packages as unreferenced

### ISSUE THREAD

**Issue by smira** [smira/aptly#217]
It has been introduced in #154: snapshot merge and aptly db cleanup are using the same `RefList.Merge` function.

DB cleanup requires all package refs to be present.

**Comment by smira** [comment]
Fixed in `master`, nightly build `aptly_0.9+2+ge63adff`.

**Comment by antonio** [comment]
Thanks a lot for the quick turnaround!

**Comment by smira** [comment]
0.9.1 has been released with the fix.

**Comment by antonio** [comment]
@smira I'm afraid I'm still experiencing issues with this. 

As suggested, I added the packages to a temporary repo to rebuild the database entries but now I'm getting errors related to the source packages, ie `ERROR: unable to search: unable to load package with key Psource dovecot 1:1.2.15-7 7ba20e16ddef6b73: key not found`.

`db cleanup` is also failing:

```
# aptly db cleanup
Loading mirrors, local repos, snapshots and published repos...
Loading list of all packages...
Deleting unreferenced packages (0)...
Building list of files referenced by packages...
ERROR: key not found
```

Is there anything I can try to get this fixed? Thanks in advance.

**Comment by smira** [comment]
@antonio it could be with any package (including `source` as well), could you please try adding it to empty repo as well?

I'll provide more flags to `aptly db cleanup` to make output easier to read.

**Comment by antonio** [comment]
@smira unfortunately adding the packages to an empty repo does not work for all of them, it seems :pensive:

**Comment by smira** [comment]
You should have had conflicting packages, so you have many variants of the same name-version-arch package. So you need to guess which one to add :(

If you have all of them published, in theory you can create many empty repos and add each published package file to each repo (you can't add all of them into single repo, as they're conflicting).

Let me see if I can make better `aptly db cleanup` command today.

**Comment by smira** [comment]
@antonio could you please try installing nightly build `aptly_0.9.5~dev+4+g03e2a8d` (https://www.aptly.info/download/ nightly repo) and running `aptly db cleanup -dry-run -verbose`? It should report all missing package references.

**Comment by antonio** [comment]
This might take a while to fix :sweat_smile: 

```
~ # aptly db cleanup -dry-run -verbose | tee /tmp/aptly-db-cleanup.log | wc -l
64440
```

**Comment by antonio** [comment]
Oh actually the list of unresolvable package references is not that bad, let's see if I can work something out to fix it.

**Comment by smira** [comment]
Oh... :(

**Comment by smira** [comment]
@antonio could you please try nightly build `aptly_0.9.5~dev+11+gd5c6f0b`: `aptly db cleanup -verbose -dry-run` should repo sources of those unreferenced package (which snapshots/repos/... have those broken references).

**Comment by antonio** [comment]
@smira thanks a lot, I've finally managed to get it fixed by deleting the published repos using the new `force-drop` option and recreating them.

```
~ # aptly db cleanup
Loading mirrors, local repos, snapshots and published repos...
Loading list of all packages...
Deleting unreferenced packages (1)...
Building list of files referenced by packages...
Building list of files in package pool...
Deleting unreferenced files (63597)...
Disk space freed: 51.10 GiB...
Compacting database...
```

**Comment by smira** [comment]
@antonio that's great... sorry for the bug in the first place... now aptly has integration test verifying that it won't happen in the future.
